### ISSUE TITLE
list works and download returns a blank line

### ISSUE THREAD

**Issue by ghost** [darrenparkinson/wt#1]
Hi Darren,

Question: I've got my domain from WebEx.  I've tried the primary and secondary.  wt list works fine, but when I do download it just returns a blank line with no errors.

Thoughts on that?

Best,
Jack

**Comment by darrenparkinson** [comment]
It’s specifically the nbr domain rather than the tenant? Something like nln1wss1 or something. Seems like they mainly start with an n. Is that what you’re using? I haven’t really be able to test it since uploading it for someone else since the sandbox won’t let me download as I’m not a site admin. The person I uploaded it for did use it successfully though.

**Comment by ghost** [comment]
I figured it out - if you've got special chars in the password or @ in the username, need to be extra careful escaping everything.  The NBR API seemed especially fragile due to that.  I've got it working now.  Appreciate you taking the effort to do this, really helped me out!

**Comment by darrenparkinson** [comment]
Great. Glad you got it working. How did you come across it? Let me know if there is anything more I can help with.
